name: Restonomer CI

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging", "master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Scalafmt Check
        run: sbt scalafmtCheckAll
      - name: Run Unit Tests
        run: sbt test
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Integration Tests
        run: sbt IntegrationTest/test
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Coverage Report
        run: sbt coverageReport coverageAggregate
